name: Build and push to AWS Staging branch

on:
  push:
    branches: [ staging ]

jobs:

    deploy:
    
        name: Setup AWS Account
        runs-on: ubuntu-latest
        env:
          #IMAGE_NAME: 626774426159.dkr.ecr.eu-north-1.amazonaws.com/django-dev/v${{ github.sha }}
          DEVELOPMENT_MODE: "True"
        steps:

        - name: Check Out Repo 
          uses: actions/checkout@v2
        
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-north-1

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install req
          run: pip install -r requirements.txt

        - name: Migrate
          run: python manage.py migrate
        
        - name: Run Test
          run: (python manage.py test) || true

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
          
        - name: Build and Push Docker image
          env:
             ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
             ECR_REPOSITORY: django-dev
             IMAGE_TAG: ${{ github.sha }}
          run: |
             docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
             docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
             docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

        #- name: Create New Instance Template
        #  run: gcloud compute instance-templates create-with-container instance-template-${{ github.sha }} --tags=http-server --container-env=DATABASE_URL=${{ secrets.DB_URL }} --container-image=gcr.io/cloud-run-dev-328005/cloud-run-dev/v${{ github.sha }}:latest
        
        #- name: Edit Instance Group with new Instance Template
        #  run: gcloud compute instance-groups managed set-instance-template instance-group-1 --zone=europe-west4-a --template=instance-template-${{ github.sha }}

        
        #  
        #- name: Recreate Instances
        #  run: gcloud compute --project "${{ secrets.GCR_DEV_PROJECT_ID }}" instance-groups managed recreate-instances "instance-group-1" --zone "europe-west4-a" --instances "instance-group-1-6k84"
