name: Build and push to GCR Staging branch

on:
  push:
    branches: [ staging ]

jobs:

    deploy:
    
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:

          #IMAGE_NAME: gcr.io/${{ secrets.GCR_DEV_PROJECT_ID }}/${{ secrets.GCR_DEV_APP_NAME }}-ver-${{ github.sha }}
          IMAGE_NAME: gcr.io/cloud-run-dev-328005/cloud-run-dev/v${{ github.sha }}
          DEVELOPMENT_MODE: "True"
        steps:

        - name: Check Out Repo 
          uses: actions/checkout@v2
        
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCR_DEV_PROJECT_ID }}
            service_account_email: ${{ secrets.GCR_DEV_SERVICE_NAME }}
            service_account_key: ${{ secrets.GCR_DEV_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2
        
        #- name: Install Mysql Python Client
        #  run: sudo apt-get update && sudo apt-get install -y python3-mysqldb 

        - name: Install req
          run: pip install -r requirements.txt

        - name: Migrate
          run: python manage.py migrate
        
        - name: Run Test
          run: (python manage.py test) || true
          
        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Create New Instance Template
          run: gcloud compute instance-templates create-with-container instance-template-${{ github.sha }} --tags=http-server --container-env=DATABASE_URL=${{ secrets.DB_URL }} --container-image=gcr.io/cloud-run-dev-328005/cloud-run-dev/v${{ github.sha }}:latest
        
        - name: Edit Instance Group with new Instance Template
          run: gcloud compute instance-groups managed set-instance-template instance-group-1 --zone=europe-west4-a --template=instance-template-${{ github.sha }}
          
        #- name: Recreate Instances
        #  run: gcloud compute --project "${{ secrets.GCR_DEV_PROJECT_ID }}" instance-groups managed recreate-instances "instance-group-1" --zone "europe-west4-a" --instances "instance-group-1-6k84"
